a=int(input("enter any num"))
b=float(input("enter any float num"))
c=complex(input("enter any complex num"))
d=(input("enter any string"))
e=bool(input("enter any bool"))
f=eval(input("enter list ele like [1,2]"))
g=eval(input("enter tuple like(1,2)"))
h=bytes([65,97,100])
i=bytearray([66,98,101])
j=None
k=range(1,10)

print(type(a))
print(type(b))
print(type(c)) 
print(type(d))
print(type(e))
print(type(f))
print(type(g))
print(type(h)) 
print(type(i))
print(type(j))
print(type(k))
print(a,",",b,",",c,",",d,",",e,",",f,",",g,",",h,",",i,",",j,",",k)