name=input("enter your name ")
age=int(input("enter your age"))
marks=float(input("enter your marks percentage:"))
print("name :",name ,",age:",age,",marks:",marks)
print(type(name),  type(age),  type(marks))